# Generated by Django 6.0.1 on 2026-01-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='codigo_rastreio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='link_fornecedor',
            field=models.URLField(blank=True, help_text='Link interno - nunca mostrar ao cliente', null=True),
        ),
    ]
