# Generated by Django 6.0.1 on 2026-01-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_pedido_codigo_rastreio_alter_produto_link_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='dimensoes',
            field=models.CharField(blank=True, help_text='Ex: 6cm x 6cm x 8cm', max_length=100),
        ),
        migrations.AddField(
            model_name='produto',
            name='garantia',
            field=models.CharField(blank=True, default='3 meses', max_length=100),
        ),
        migrations.AddField(
            model_name='produto',
            name='marca',
            field=models.CharField(blank=True, default='AcheiProGato', max_length=100),
        ),
        migrations.AddField(
            model_name='produto',
            name='material',
            field=models.CharField(blank=True, help_text='Ex: PC + Silicone', max_length=100),
        ),
        migrations.AddField(
            model_name='produto',
            name='origem',
            field=models.CharField(blank=True, default='Importado', max_length=100),
        ),
        migrations.AddField(
            model_name='produto',
            name='recomendacao_raca',
            field=models.CharField(blank=True, default='Todas as raças', max_length=100),
        ),
    ]
