# Generated by Django 6.0.1 on 2026-01-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_produto_dimensoes_produto_garantia_produto_marca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('brinquedos', 'Brinquedos'), ('higiene', 'Higiene'), ('alimentacao', 'Alimentação'), ('conforto', 'Conforto')], default='brinquedos', max_length=50),
        ),
        migrations.AddField(
            model_name='produto',
            name='mais_vendido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_antigo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço antes da promoção', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='promocao',
            field=models.BooleanField(default=False),
        ),
    ]
