# Generated by Django 6.0.1 on 2026-01-26 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_produto_categoria_produto_mais_vendido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='dimensoes',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='garantia',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='link_fornecedor',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='mais_vendido',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='preco_antigo',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='preco_fornecedor',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='promocao',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='recomendacao_raca',
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao_curta',
            field=models.TextField(default='texto', help_text='Fica ao lado da foto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao_detalhada',
            field=models.TextField(default='texto temporario', help_text='Fica na parte inferior da página'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produto',
            name='marca',
            field=models.CharField(default='Genérico', max_length=100),
        ),
        migrations.AlterField(
            model_name='produto',
            name='material',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='produto',
            name='origem',
            field=models.CharField(default='Importado', max_length=100),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comentario', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='store.produto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='produtos/')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='store.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Variacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('valor', models.CharField(max_length=50)),
                ('estoque_especifico', models.PositiveIntegerField(default=0)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='store.produto')),
            ],
        ),
    ]
