# Generated by Django 6.0.1 on 2026-01-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_produto_ativo_remove_produto_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('brinquedos', 'Brinquedos'), ('alimentacao', 'Alimentação'), ('conforto', 'Conforto'), ('higiene', 'Higiene')], default='brinquedos', max_length=100),
        ),
        migrations.AddField(
            model_name='produto',
            name='dimensoes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='garantia',
            field=models.CharField(default='3 meses', max_length=100),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
        migrations.AddField(
            model_name='produto',
            name='link_fornecedor',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='mais_vendido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_fornecedor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='promocao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='recomendacao_raca',
            field=models.CharField(default='Todas as raças', max_length=100),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao_curta',
            field=models.TextField(help_text='Lista de benefícios (Sobre este item)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao_detalhada',
            field=models.TextField(help_text='Descrição completa do produto'),
        ),
    ]
