# Generated by Django 6.0.1 on 2026-01-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_avaliacao_nota_alter_avaliacao_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('brinquedos', 'Brinquedos'), ('alimentacao', 'Alimentação'), ('conforto', 'Caminhas e Conforto'), ('higiene', 'Higiene')], default='brinquedos', max_length=100),
        ),
    ]
