# Generated by Django 6.0.1 on 2026-01-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_pedido_bairro_pedido_cep_pedido_cidade_pedido_estado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variacao',
            old_name='estoque_especifico',
            new_name='estoque_specifico',
        ),
        migrations.AddField(
            model_name='variacao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/variacoes/'),
        ),
    ]
