# Generated by Django 6.0.1 on 2026-01-29 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_estoque_especifico_variacao_estoque_specifico_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variacao',
            old_name='estoque_specifico',
            new_name='estoque_especifico',
        ),
    ]
