# Generated by Django 6.0.1 on 2026-01-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_rename_estoque_specifico_variacao_estoque_especifico'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacao',
            name='cor_codigo',
            field=models.CharField(blank=True, help_text='Ex: #0000FF para azul', max_length=20, null=True),
        ),
    ]
