# Generated by Django 6.0.1 on 2026-01-29 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_variacao_cor_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='variacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.variacao'),
        ),
    ]
