# Generated by Django 6.0.1 on 2026-01-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_itempedido_variacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='frete',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
