# Generated by Django 6.0.1 on 2026-01-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_pedido_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('pendente', 'Aguardando Pagamento'), ('pago', 'Pago - Preparando Envio'), ('em_separacao', 'Em Separação (Compra na Fonte)'), ('enviado', 'Enviado / Em Transporte'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
    ]
