# Generated by Django 6.0.1 on 2026-01-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
